# Generated by Django 4.2.6 on 2023-10-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_userprofile_followers_following_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='apis.userprofile', verbose_name='User'),
        ),
    ]
